### PR TITLE
SLT-800: Improve Cron logging

### PR DESCRIPTION
**Pull request by ragnarkurmwunder**
* Document cron job logging

### CODE REVIEW

**Review by Jancis — CHANGES_REQUESTED** [review]
Let's get the chart changes in first and set this to "Draft" until they are released. This could use some addition that explains which container logs are available in this format.

**Review by Rade333 — CHANGES_REQUESTED** [review]
I agree with the changes Janis suggested.

**Comment by Jancis** [comment]
This PR can be updated now to reflect to configuration schema changes

**Comment by Rade333** [comment]
Closing as this PR does not seem relevant anymore since we skipped the json format.

**Pull request closed without merging**
