### PR TITLE
Fix the PUBLIC_FILES_PATH value.

### PR DESCRIPTION
**Pull request by tormi**

### CODE REVIEW

**Comment by Jancis** [comment]
Why do You propose such change?
Also - never link internal resources in public repository.

**Comment by tormi** [comment]
Sorry for the link to the internal repo. It was pointing to the D7 project where full path as described in here as an example broke the site.

**Comment by tormi** [comment]
Okay, thanks for the feedback. Resolved the issue in the project level.

**Comment by Jancis** [comment]
No project has had issues with the [default value](https://github.com/wunderio/charts/blob/master/drupal/values.yaml#L371) and this doc suggests setting the same exact value for migrated mount. There has to be some special modification that breaks the site.

**Comment by tormi** [comment]
@Jancis, thanks for your patience with me ;) I found out what the reason was - I'm using `$conf['file_public_path']` in that Drupal 7 project and that doesn't use the full path and therefore breaks the site.

The fix is to start using `$settings['file_public_path']` in D7 sites as well.

Once again, thanks for your efforts!

**Comment by Jancis** [comment]
Okay, thanks for clearing that up! If this is something we should add to D7 [settings.php extension template](https://github.com/wunderio/charts/blob/master/drupal/files/settings.silta.d7.php), shout.

**Pull request closed without merging**
