### PR TITLE
Add example of multiple encrypted files

### PR DESCRIPTION
**Pull request by kirkkala**
Thanks @TomiMikola for pointing me how to add multiple secrets ([Slack message](https://wunder.slack.com/archives/C8UN6AG9W/p1646742263847669?thread_ts=1646742108.870309&cid=C8UN6AG9W))

This would add it on documentation as well.

### CODE REVIEW

**Comment by Jancis** [comment]
Please use commas (no whitespace, just comma) to separate values

**Review by Jancis — APPROVED** [review]

**Comment by TomiMikola** [comment]
> Please use commas (no whitespace, just comma) to separate values

Yes! Commas would definitely be to expected approach but it doesn't work. Would be highly appreciated if someone has the skills and time to make the `decrypt_files` to handle comma-separated values too.

**Comment by Jancis** [comment]
Based on [the code](https://github.com/wunderio/silta-circleci/blob/master/orb/commands/%40common.yml#L342), I assumed this should work:
```
silta/decrypt-files:
  files: silta/secrets,silta/some-other-secrets
```
Note: notice there is no extra whitespace after `,`, even though it would look better.

**Comment by badrange** [comment]
In our project we have this -  not sure if we ever tried properly with comma separated values
```
            - silta/decrypt-files:
                files: silta/silta-prod-secrets.yml
                secret_key_env: IND_SECRET_KEY
            - silta/decrypt-files:
                files: silta/gcloud-service-prod.json
                secret_key_env: IND_SECRET_KEY
```

**Comment by kirkkala** [comment]
@Jancis 
> Based on [the code](https://github.com/wunderio/silta-circleci/blob/master/orb/commands/%40common.yml#L342), I assumed this should work:

Yes. but did not work like @TomiMikola also pointed out. This is the circleci output when comma separating without space like this `files: silta/secrets-prod,silta/secrets-prod-certs`
```
Decrypting secrets
silta/secrets-prodsilta/secrets-prod-certs
Can't open silta/secrets-prodsilta/secrets-prod-certs for reading, No such file or directory
```

--- 
@[badrange](https://github.com/badrange) interesting approach, maybe we _could_ document that as well but since the key is plural `files` it would sound reasonable to allow multiple files in it. But I leave it now for @Jancis to decide if the code should be fixed to really work with comma or do we keep it this way, separated with space which clearly works ATM.

**Comment by Jancis** [comment]
Indeed, it turned out space delimited values are required.

There's a PR now, that will allow space delimited values for backwards compatibility and comma separated too. Allows even mixed values of coma, whitespace and combination of both like `silta/secret1 silta/secret2,silta/secret3, silta/secret4`

This will work with both options, codebase-build steps and decrypt_files parameter:
```yaml
jobs:
  - silta/drupal-build-deploy:
      codebase-build:
        # Option A
        - silta/decrypt-files:
            files: silta/secret1 silta/secret2,silta/secret3, silta/secret4
      # Option B
      decrypt_files: silta/secret1 silta/secret2,silta/secret3, silta/secret4
```
Related PR: https://github.com/wunderio/silta-circleci/pull/152

**Review by Jancis — CHANGES_REQUESTED** [review]
Related PR is merged, please update documentation example when possible, @kirkkala

**Review by Jancis — APPROVED** [review]
Thank You!

**Pull request merged**
